spring.application.name=kindy

mybatis.configuration.map-underscore-to-camel-case=true
mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.type-aliases-package=org.kidscafe.kindy.dto

spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

kindy.transcription.url=${WHISPER_URL}
kindy.encrypt.key=${AES_KEY}
kindy.encrypt.salt=${SALT}