spring.application.name=kindy

mybatis.configuration.map-underscore-to-camel-case=true
mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.type-aliases-package=org.kidscafe.kindy.dto

spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.mail.host=smtp.gmail.com
spring.mail.port=465
spring.mail.username=${SMTP_USERNAME}
spring.mail.password=${SMTP_PASSWORD}
spring.mail.default-encoding=UTF-8
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com

kindy.stt.url=${STT_URL}
kindy.llm.url=${LLM_URL}
kindy.llm.model=${LLM_MODEL}
kindy.llm.prompt=${LLM_PROMPT:}
kindy.tts.url=${TTS_URL}
kindy.sts.url=${STS_URL}
kindy.sts.model=${STS_MODEL}
kindy.encrypt.key=${AES_KEY}
kindy.encrypt.salt=${SALT}