package org.kidscafe.kindy.config;

import jakarta.servlet.FilterChain;
import jakarta.servlet.ServletException;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.http.HttpMethod;
import org.springframework.http.MediaType;
import org.springframework.stereotype.Component;
import org.springframework.web.filter.OncePerRequestFilter;

import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.Arrays;
import java.util.List;

/**
 * Cross-site request forgery defence for /api.
 *
 * Authentication here is a session cookie, which the browser attaches to a request no matter who
 * caused it to be sent. Without a check of some kind, any page on the internet can POST a form to
 * this API and have it run as whoever is logged in — the classic CSRF shape, and the reason the
 * state-changing endpoints below need more than a session lookup.
 *
 * <h2>Why an origin check rather than synchronizer tokens</h2>
 * The usual answer is a per-session token echoed back in a header. That needs a token endpoint, a
 * place to keep it, and a change at every call site — and this codebase has around sixty endpoints
 * that each guard themselves inline, plus a frontend fetch wrapper that would have to learn about
 * it. An origin check is one file and touches no endpoint. {@code Origin} is set by the browser on
 * every cross-origin request and on same-origin POSTs, and page JavaScript cannot forge it: it is
 * on the forbidden-header list precisely so it can be trusted for this.
 *
 * <p>The allowlist is {@code kindy.cors.allowed-origins}, the same list {@link CorsConfig} reads.
 * An origin trusted to make credentialed cross-origin calls is exactly an origin trusted to POST,
 * so sharing the list keeps the two from drifting apart. In production the SPA is served from this
 * same application, so same-origin requests are the normal case and the list only covers the Vite
 * dev server.
 *
 * <h2>What is deliberately not checked</h2>
 * Safe methods (GET/HEAD/OPTIONS) pass through. They are not supposed to change state, and CORS
 * already stops another origin from reading the response.
 *
 * <p>Requests carrying neither {@code Origin} nor {@code Referer} pass through as well. Browsers
 * send {@code Origin} on the POSTs we care about; a request with neither is a non-browser client
 * (curl, a health check, a server-to-server call) and has no ambient session cookie to abuse in
 * the first place. Rejecting them would break tooling without closing anything.
 *
 * @see CorsConfig for the matching cross-origin read policy
 */
@Slf4j
@Component
public class CsrfFilter extends OncePerRequestFilter {
    /**
     * The OAuth callback is cross-site by design — the browser arrives on it straight from the
     * authorization server, so its {@code Origin}/{@code Referer} is kauth.kakao.com or similar and
     * could never be on our allowlist. It is not unprotected: it is a GET that carries a one-time
     * {@code state} generated by us and held in the session, which is the CSRF defence the OAuth
     * spec prescribes for exactly this hop. Listed here so the exemption is a decision on the
     * record rather than a side effect of the safe-method rule above.
     */
    private static final String OAUTH_CALLBACK_SUFFIX = "/callback";
    private static final String OAUTH_PATH_PREFIX = "/api/user/oauth/";
    private static final String API_PATH_PREFIX = "/api/";

    private final List<String> allowedOrigins;

    CsrfFilter(@Value("${kindy.cors.allowed-origins}") String allowedOrigins) {
        this.allowedOrigins = Arrays.asList(allowedOrigins.split("\\s*,\\s*"));
    }

    @Override
    protected boolean shouldNotFilter(HttpServletRequest request) {
        String path = request.getRequestURI();

        // Only the API is session-authenticated, so only the API can be forged against. Once the
        // SPA is served from this same application everything outside /api is a static asset.
        if (!path.startsWith(API_PATH_PREFIX)) return true;

        return path.startsWith(OAUTH_PATH_PREFIX) && path.endsWith(OAUTH_CALLBACK_SUFFIX);
    }

    @Override
    protected void doFilterInternal(HttpServletRequest request, HttpServletResponse response, FilterChain chain)
            throws ServletException, IOException {

        if (isSafeMethod(request.getMethod()) || isTrustedOrigin(request)) {
            chain.doFilter(request, response);
            return;
        }

        log.info("Rejected cross-origin {} {} from origin={} referer={}",
                request.getMethod(), request.getRequestURI(),
                request.getHeader("Origin"), request.getHeader("Referer"));

        // The frontend unwraps every /api response as a ResultDTO envelope, so answering with one
        // keeps this a normal ApiError at the call site instead of a JSON parse failure.
        response.setStatus(HttpServletResponse.SC_FORBIDDEN);
        response.setContentType(MediaType.APPLICATION_JSON_VALUE);
        response.setCharacterEncoding("UTF-8");
        response.getWriter().write("{\"status\":\"error\",\"code\":\"INVALID_ORIGIN\"}");
    }

    private boolean isSafeMethod(String method) {
        return HttpMethod.GET.matches(method)
                || HttpMethod.HEAD.matches(method)
                || HttpMethod.OPTIONS.matches(method);
    }

    /**
     * {@code Origin} is the header we want; {@code Referer} is the fallback for the handful of
     * cases that omit it. Referer carries a whole URL, so it is reduced to scheme://host:port
     * before comparison — matching on a prefix instead would let {@code https://kindies.kr.evil.com}
     * through.
     */
    private boolean isTrustedOrigin(HttpServletRequest request) {
        String origin = request.getHeader("Origin");
        if (origin == null) {
            String referer = request.getHeader("Referer");
            if (referer == null) return true;   // not a browser — see class javadoc
            origin = toOrigin(referer);
            if (origin == null) return false;   // a Referer we cannot parse is not one we trust
        }

        return allowedOrigins.contains(origin) || origin.equals(ownOrigin(request));
    }

    /** Reduces an absolute URL to its scheme://host[:port] origin, or null if it will not parse. */
    private String toOrigin(String url) {
        try {
            URI uri = new URI(url);
            if (uri.getScheme() == null || uri.getHost() == null) return null;
            String origin = uri.getScheme() + "://" + uri.getHost();
            return uri.getPort() == -1 ? origin : origin + ":" + uri.getPort();
        } catch (URISyntaxException e) {
            return null;
        }
    }

    /**
     * The origin this request was addressed to. Same-origin POSTs are the normal case once the SPA
     * ships inside this JAR, and they would otherwise need the production hostname duplicated into
     * the allowlist just to talk to itself.
     *
     * <p>Derived from the request rather than configured, which is safe in a way that a redirect
     * URI would not be: a forged Host header only ever lets a request match *itself*, and an
     * attacker's page cannot set the Origin header its browser sends.
     */
    private String ownOrigin(HttpServletRequest request) {
        String scheme = request.getScheme();
        int port = request.getServerPort();
        boolean defaultPort = ("http".equals(scheme) && port == 80) || ("https".equals(scheme) && port == 443);
        return defaultPort
                ? scheme + "://" + request.getServerName()
                : scheme + "://" + request.getServerName() + ":" + port;
    }
}
